//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;

using QuickZ.Persistent.Base.Mails;
using QuickZ.Persistent.Base.Documents;
using QuickZ.Persistent.BaseImpl.Mailings;

namespace QuickZ.Persistent.BaseImpl
{
    [DefaultProperty("Name")]
    public partial class BusinessDocumentGroup : XPObject, IBusinessDocumentGroup
    {
        // Fields...
        private string _Name;

        [Size(SizeAttribute.DefaultStringMappingFieldSize)]
        public string Name
        {
            get
            {
                return _Name;
            }
            set
            {
                SetPropertyValue("Name", ref _Name, value);
            }
        }

        //[Association("BusinessDocumentGroups-BusinessDocumentFiles")]
        //public XPCollection<BusinessDocumentData> Documents
        //{
        //    get
        //    {
        //        return GetCollection<BusinessDocumentData>("Documents");
        //    }
        //}

        // [Association("BusinessDocumentGroups-Templates")]
        //public IList<IMailMergeTemplate> Templates
        //{
        //    get
        //    {
        //        //return GetCollection<IMailMergeTemplate>("RegularTemplates");
        //        return new XPCollection<MailMergeTemplateBase>(Session, CriteriaOperator.Parse("", this.Oid)).ToList(); ;
        //    }
        //}

        //[Association("BusinessDocumentGroups-UserTemplates")]
        //public XPCollection<MailMergeRegularUserTemplate> UserTemplates
        //{
        //    get
        //    {
        //        return GetCollection<MailMergeRegularUserTemplate>("UserTemplates");
        //    }
        //}

        [Browsable(false)]
        public IList<IMailMergeTemplate> Templates
        {
            get
            {
                return MailMergeTemplateBases as IList<IMailMergeTemplate>;
            }
        }

        [Browsable(false)]
        public IList<IBusinessDocument> Documents
        {
            get
            {
                return BusinessDocuments as IList<IBusinessDocument>;
            }
        }

        [DevExpress.ExpressApp.DC.XafDisplayName("Templates")]
        [Association("BusinessDocumentGroups-MailMergeTemplateBases")]
        public XPCollection<MailMergeTemplateBase> MailMergeTemplateBases
        {
            get
            {
                return GetCollection<MailMergeTemplateBase>("MailMergeTemplateBases");
            }
        }

        [DevExpress.ExpressApp.DC.XafDisplayName("Documents")]
        [Association("BusinessDocumentGroups-BusinessDocumentData")]
        public XPCollection<BusinessDocumentData> BusinessDocuments
        {
            get
            {
                return GetCollection<BusinessDocumentData>("BusinessDocuments");
            }
        }

    }

}
